FROM tibalt/alpine-node:rpi

RUN [ "cross-build-start" ]

WORKDIR /app

USER app

RUN \
git clone --depth=1 https://github.com/darkwebdev/mozaik-dashboard dashboard && \
cd dashboard && \
npm i

USER root

RUN [ "cross-build-end" ]

COPY ./app /app

EXPOSE 5000

USER app

ENTRYPOINT ["/app/entry.sh"]
