FROM tibalt/alpine-node:rpi

RUN [ "cross-build-start" ]

WORKDIR /app

RUN \
git clone --depth=1 https://github.com/darkwebdev/mozaik-dashboard dashboard && \
cd dashboard && \
npm i

RUN chown app:users /app/dashboard

RUN [ "cross-build-end" ]

COPY ./app /app

EXPOSE 5000

USER app

ENTRYPOINT ["sh", "/app/entry.sh"]
