FROM tibalt/alpine-node:rpi

WORKDIR /app

USER app

RUN [ "cross-build-start" ]

RUN \
git clone --depth=1 https://github.com/darkwebdev/mozaik-dashboard dashboard && \
cd dashboard && \
npm i

RUN [ "cross-build-end" ]

COPY ./app /app

EXPOSE 5000

ENTRYPOINT ["/app/entry.sh"]
